/*
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by generate_java_rpc.js, do not edit manually.

package com.microsoft.playwright.impl;

import java.util.List;

class SerializedArgument{
  SerializedValue value;
  Channel[] handles;
}

class FrameExpectOptions {
  Object expressionArg;
  List<ExpectedTextValue> expectedText;
  Double expectedNumber;
  SerializedArgument expectedValue;
  Boolean useInnerText;
  boolean isNot;
  Double timeout;
}

class FrameExpectResult {
  boolean matches;
  SerializedValue received;
  List<String> log;
}


